- src/hist1d.jl
Remove the useless "frequency" label and add the total count--very useful to verify at a glance that you filled it with the right number of events.
Before
```julia
julia> Hist1D(randn(100), -3:3)
┌                              ┐
[-3.0, -2.0) ┤▇ 1
[-2.0, -1.0) ┤▇▇▇▇▇▇▇▇▇▇ 14
[-1.0,  0.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 35
[ 0.0,  1.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 37
[ 1.0,  2.0) ┤▇▇▇▇▇▇▇ 10
[ 2.0,  3.0) ┤▇ 1
└                              ┘
Frequency
edges: -3:3
bin counts: [1, 14, 35, 37, 10, 1]
```
After
```julia
julia> Hist1D(randn(100), -3:3) 
┌                              ┐
[-3.0, -2.0) ┤▇▇▇ 4
[-2.0, -1.0) ┤▇▇▇▇▇▇▇▇ 13
[-1.0,  0.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 41
[ 0.0,  1.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 22
[ 1.0,  2.0) ┤▇▇▇▇▇▇▇▇▇▇ 16
[ 2.0,  3.0) ┤▇▇▇ 4
└                              ┘
edges: -3:3
bin …
```
> add total count to show()

- src/arithmatics.jl
- src/hist1d.jl
- test/runtests.jl
Closes https://github.com/Moelf/FHist.jl/issues/8 and https://github.com/Moelf/FHist.jl/issues/7
Changes
* `Hist1D` default constructor set sumw2 equal to the counts (weight=1)
* single `push!()` with optional weight=1
* `Hist1D(A::AbstractVector, r::AbstractRange{T})` (regular binning) also computes sumw2 in the loop
* `Hist1D(A, wgts::AbstractWeights, edges::AbstractVector)` (irregular binning) runs `fit(Histogram, ...)` twice: once with regular counts and again with `weights^2`. The latter is fed into the default `Hist1D` constructor as sumw2.
Now histogram arithmetic test cases from ROOT work for regular and irregular binning with and without specified weights.
> Always compute/store sumw2

- src/FHist.jl
- src/hist1d.jl
- test/runtests.jl
Closes https://github.com/Moelf/FHist.jl/issues/11
* Factored out bin calculation logic for float range, int range, irregular binning.
* Added `empty!()` to reset hists
* Added thread-UNsafe `unsafe_push!()`
* Defined `Base.broadcastable(h::Hist1D) = Ref(h)` so one can do `push!.(h, [-3.0, -2.9, -2.8])` or `push!.(h, [-3.0, -2.9, -2.8], 2.0)` as a "broadcasted push".
```julia
julia> using Revise, FHist, BenchmarkTools, StatsBase, StatProfilerHTML
julia> a = randn(10^6);
julia> @benchmark Hist1D(a, -3:0.1:3)
BechmarkTools.Trial: 1239 samples with 1 evaluations.
Range (min … max):  3.577 ms …   5.555 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     3.957 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   4.024 ms ± 271.173 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
Memory …
```
> factor out bin calculation and optimize push!()

- src/hist1d.jl
Now every method to fill a `Hist1D` goes through `unsafe_push!()`
> more consolidation

- src/hist1d.jl
- test/runtests.jl
* combined the AbstractFloat and Integer implementations. 
* swapped the `+0.5`/`round` for just `floor` based on what I saw in https://github.com/joshday/OnlineStats.jl/blob/master/src/stats/histograms.jl. Though if I benchmark their hist, it's ~3-4x slower than FHist, probably related to them not using `@inline`. 3-4x is the speedup I observed when adding `@inline` in front of `unsafe_push!()`
* the `ifelse` chain evidently wasn't even triggering simd, so the implementation is simpler now.
`-3:0.1:3` is slightly faster, and `-3:3` is even faster (and 8x faster than master).
Before (`master`):
```julia
julia> a = randn(10^6);
julia> @benchmark Hist1D(a, -3:0.1:3)
BechmarkTools.Trial: 1142 samples with 1 evaluations.
Range (min … max):  3.839 ms …   6.746 ms  ┊ GC (min … max): 0.00% … …
```
> optimize int binning

- src/hist1d.jl
- test/runtests.jl
Add a simple specialized `_edge_binindex(r::AbstractRange{<:Integer}, x::Integer) = return x - first(r) + 1`
```julia
julia> a = floor.(Int,abs.(randn(10^6).*2));
julia> Hist1D(a, 0:10)
┌                              ┐
[ 0.0,  1.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 382988
[ 1.0,  2.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 300585
[ 2.0,  3.0) ┤▇▇▇▇▇▇▇▇▇▇▇ 183317
[ 3.0,  4.0) ┤▇▇▇▇▇ 87695
[ 4.0,  5.0) ┤▇▇ 33310
[ 5.0,  6.0) ┤▇ 9477
[ 6.0,  7.0) ┤ 2167
[ 7.0,  8.0) ┤ 375
[ 8.0,  9.0) ┤ 79
[ 9.0, 10.0) ┤ 7
└                              ┘
edges: 0:10
bin counts: [382988, 300585, 183317, 87695, 33310, 9477, 2167, 375, 79, 7]
total count: 1000000
```
```julia
julia> @benchmark Hist1D(a, 0:10)
BechmarkTools.Trial: 2060 samples with 1 evaluations.
Range (min … max):  2.276 ms …   4.540 ms  ┊ GC (min … max): 0.00% … 0.00% …
```
> optimize integer binning

- src/FHist.jl
- src/hist1d.jl
- test/runtests.jl
Adding another feature from https://github.com/Moelf/FHist.jl/issues/13.
```julia
julia> using FHist
julia> h = Hist1D(randn(10^3))
┌                              ┐
[-3.0, -2.5) ┤ 1
[-2.5, -2.0) ┤▇ 11
[-2.0, -1.5) ┤▇▇▇▇▇ 44
[-1.5, -1.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇ 101
[-1.0, -0.5) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 160
[-0.5,  0.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 203
[ 0.0,  0.5) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 186
[ 0.5,  1.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 147
[ 1.0,  1.5) ┤▇▇▇▇▇▇▇▇▇▇▇ 91
[ 1.5,  2.0) ┤▇▇▇▇ 32
[ 2.0,  2.5) ┤▇▇ 20
[ 2.5,  3.0) ┤ 4
└                              ┘
edges: -3.0:0.5:3.0
bin counts: [1, 11, 44, 101, 160, 203, 186, 147, 91, 32, 20, 4]
total count: 1000
```
```julia
julia> rebin(h, 2)
┌                              ┐
[-3.0, -2.0) ┤▇ 12
[-2.0, -1.0) ┤▇▇▇▇▇▇▇▇▇▇ 145
[-1.0,  0.0) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 363
[ …
```
> add rebinning method

- src/hist1d.jl
- test/runtests.jl
Closes https://github.com/Moelf/FHist.jl/issues/26.
Implement `show` for `"text/html"` to get:
Despite google and several threads talking about `context=:compact=>true`, I had to dig into `Base.show_vector` to realize it is `:limit`:
`repr(bincounts(h), context=:limit => true)` gives the properly elided string
`"[10, 6, 10, 12, 13, 19, 26, 35, 45, 49 … 2, 3, 6, 4, 1, 3, 0, 0, 0, 1]"`
> svg repr in notebooks

- src/FHist.jl
- src/hist1d.jl
- test/runtests.jl
Addresses another item in https://github.com/Moelf/FHist.jl/issues/13. Add 
```julia
restrict(h::Hist1D, low=-Inf, high=Inf)
```
and also a curried version for, e.g., `h |> restrict(0.5, 3) |> median`.
> add restrict method

- src/hist1d.jl
- test/runtests.jl
Closes https://github.com/Moelf/FHist.jl/issues/41
After int-dividing by `step(r)`, we still get the same performance for
```julia
julia> a = randn(10^6);
julia> @benchmark Hist1D(a, -3:3)
BechmarkTools.Trial: 2016 samples with 1 evaluations.
Range (min … max):  2.323 ms …   4.203 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     2.439 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   2.474 ms ± 131.345 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
```
so that's nice :)
> fix bug with step size

- README.md
- src/FHist.jl
- src/hist1d.jl
- src/hist2d.jl
- test/runtests.jl
Closes https://github.com/Moelf/FHist.jl/issues/16
Todo
Remaining questions
- ~better name for `overflow`? (`overflow=true` seems meaningless since `overflow` isn't a verb) `include_overflow` is too long. Should it be `clip`/`crop`/`truncate`/`cut`? Polled myself and one other person and the votes are 2 for "keep `overflow` but just make sure  to explain it in the docs"~
- ~default behavior? Right now `overflow=false` (to match `StatsBase.histogram` by default). This would be the least surprising to the user. If they want, it's easy to just `Hist1D(a, 1:3, overflow=true)`.~
> implement overflow

- README.md
- src/hist1d.jl
```diff
-    return floor(Int, (x - first(r)) / step(r)) + 1
+    return floor(Int, (x - first(r)) * inv(step(r))) + 1
```
apparently gives a ~20% speedup for histogram filling (3.1ms -> 2.5ms for randn(10^6)).
_______
If we also did 
```julia
return Base.unsafe_trunc(Int, round((x - first(r)) * inv(step(r)), RoundDown)) + 1
```
we can get another 20% (2.5ms -> 2.05ms)
`unsafe_trunc` avoids a `if $(Tf(typemin(Ti))) <= x < $(Tf(typemax(Ti)))` check. Currently we have
```julia
julia> Hist1D([-Inf,Inf,NaN], -1:0.5:1)
ERROR: InexactError: trunc(Int64, -Inf)
```
and if we used `unsafe_trunc`, we'd have
```julia
julia> Hist1D([-Inf,Inf,NaN], -1:0.5:1)
┌                              ┐
[-1.0, -0.5) ┤ 0
[-0.5,  0.0) ┤ 0
[ 0.0,  0.5) ┤ 0
[ 0.5,  1.0) ┤ 0
└                              ┘
edges: …
```
> optimize binindex calculation

- src/hist1d.jl
- src/hist2d.jl
- test/runtests.jl
When `:compact=>true` is set inside `show()`, then use a one-liner representation. Helps for histograms inside a dict, for example. Regular representation via `h`/`show(h)`/`print(h)` is unaffected and still shows the unicode plot.
Before
```julia
julia> d=Dict(
:h1=>Hist1D(randn(100)),
:h2=>Hist1D(randn(10^5))*2.5,
:h3=>Hist2D((rand(100),rand(100)))
)
Dict{Symbol, AbstractHistogram} with 3 entries:
:h1 =>                 ┌                              ┐ …
:h2 =>                 ┌                              ┐ …
:h3 =>      ┌─────┐ …
```
After
```julia
julia> d=Dict(
:h1=>Hist1D(randn(100)),
:h2=>Hist1D(randn(10^5))*2.5,
:h3=>Hist2D((rand(100),rand(100)))
)
Dict{Symbol, AbstractHistogram} with 3 entries:
:h1 => Hist1D{Int64}, edges=-4.0:1.0:3.0, integral=100
:h2 => Hist1D{Float64}, …
```
> better compact representation

- src/hist1d.jl
- test/runtests.jl
svg drawing for 1D assumes the minimum count is 0. This is not necessarily true if the histogram is a profile. If there is a bin with a negative "count" then the counts are shifted fully into range and the y=0 line is moved upward.
```julia
h = Hist2D((randn(10^6),randn(10^6)), (-3:0.1:3, -5:0.1:5))
h |> profile(:x)
```
Before
After
> move zero line when there are negative counts

- .github/workflows/ci.yml
- docs/make.jl
- docs/src/notebooks/makie_plotting.jl
- src/hist1d.jl
- src/hist2d.jl
- src/hist3d.jl
```julia
julia> @benchmark Hist1D(x, range(-1,2;length=31)) setup=x=rand(10000000)
BenchmarkTools.Trial: 85 samples with 1 evaluation.
Range (min … max):  42.596 ms … 181.668 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     47.884 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   48.218 ms ±  15.178 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%
█▅▁
███▆▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▃▇▆▄▃▃▁▁▄▁▃▁▁▁▁▁▁▁▁▅▆▆▆▃▁▁▁▃▁▃▄ ▁
42.6 ms         Histogram: frequency by time         53.7 ms <
Memory estimate: 1.00 KiB, allocs estimate: 6.
```
```julia
julia> @benchmark Hist1D(x, range(-1,2;length=31)) setup=x=rand(10000000)
BenchmarkTools.Trial: 207 samples with 1 evaluation.
Range (min … max):  12.546 ms …  13.519 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     12.810 ms               ┊ GC …
```
> Inline and optimize `push!()` when one-shot histogramming

- Project.toml
- docs/Project.toml
- docs/make.jl
- docs/src/notebooks/makie_plotting.jl
- ext/FHistCairoMakieExt.jl
- ext/FHistMakieExt.jl
- ext/FHistPlotsExt.jl
- src/FHist.jl
- src/MakieThemes.jl
@jjgomezcadenas I think we need `./ext/` for this to work
> fix pkg extention

- Project.toml
- docs/Project.toml
- docs/make.jl
- docs/src/writingtohdf5.md
- ext/FHistHDF5Ext.jl
- src/FHist.jl
- test/hdf5.jl
- test/runtests.jl
This PR allows dumping and reading to/from HDF5 files:
```julia
julia> using FHist
julia> h5dumphist
h5dumphist (generic function with 0 methods)
julia> using HDF5
[ Info: Precompiling FHistHDF5Ext [a227ba34-7673-5508-8138-4d59e86345cc]
julia> h = Hist1D(rand(1000), -3:0.3:3)
edges: -3.0:0.3:3.0
bin counts: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 311, 301, 295, 93, 0, 0, 0, 0, 0, 0]
total count: 1000
julia> h5dumphist("foo.h5", "some/path/to/myhist", h)
julia> h5readhist("foo.h5", "some/path/to/myhist", Hist1D)
edges: [-3.0, -2.7, -2.4, -2.1, -1.8, -1.5, -1.2, -0.9, -0.6, -0.3  …  0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0]
bin counts: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 311, 301, 295, 93, 0, 0, 0, 0, 0, 0]
total count: 1000
```
> Add HDF5 dump/read functionality for Hist1D/2D/3D

- ext/FHistHDF5Ext.jl
- test/hdf5.jl
I totally overlooked that `overflow` is stored as string, although the type os `Bool` which is perfectly fine in attributes.
I think we should clean that up but it's a bit embarrassing that we already need v1.1 for the format spec 🙈 On the other hand, that's what is meant for...
This PR still supports strings as `overflow` but now writes `Bool`, which cannot be read with `FHist.jl v0.10.6` without a warning (technically it's probably more likely a v2.0, but let's not exaggerate it?)
I am also not 100% happy with the version checking yet, I guess I need a tea first, it was a very short night ;)
> h5hist: write overflow as boolean but still support string

- Project.toml
I think this was forgoten in https://github.com/Moelf/FHist.jl/commit/8240850aabc6a0aee03fea5b2701fcb7fc23765c
Fixes #97
> Remove obsolete FHistCairoMakieExt ref

- Project.toml
- src/hist1d.jl
- src/hist2d.jl
- src/utils.jl
- test/runtests.jl
This shows the valid rebin values instead of throwing a modulo != 0 error.
Before:
```julia
julia> h = Hist1D(;bins=1:21, overflow=false)
edges: 1:21
bin counts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
total count: 0.0
julia> h |> rebin(3)
ERROR: AssertionError: nbins(h) % n == 0
...
julia> h2 = Hist2D((rand(10), rand(10)), (0:0.1:1, 0:0.2:1))
edges: (0.0:0.1:1.0, 0.0:0.2:1.0)
bin counts: [0 0 … 1 0; 0 0 … 1 0; … ; 0 1 … 0 0; 0 0 … 0 0]
total count: 10
julia> h2 |> rebin(3, 2)
ERROR: AssertionError: sx % nx == sy % ny == 0
...
```
after:
```julia
julia> h = Hist1D(;bins=1:21, overflow=false)
edges: 1:21
bin counts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
total count: …
```
> Add rebinning hints

- src/hist1d.jl
- src/hist2d.jl
It says the rebinning factor must be a "multiple of ...", but "power of" is correct.
> Better (actually correct) error message for rebin

- ext/FHistMakieExt.jl
- src/MakieThemes.jl
The problem was that Makie refuse to render the binedge leading to 0 under y logscale.
We replace any zero value in the `bincounts` with `eps()` since they shouldn't be visually
distinguishible for any practical purpose.
Fixs #109
> Fix edge case in plotting for empty bins in logscale

- docs/src/notebooks/makie_plotting.jl
- ext/FHistMakieExt.jl
This is an alternative to #116 @sfranchel 
~~I'm a bit hesitant to clip the error bars to positive~~
~~Blocked by https://github.com/MakieOrg/Makie.jl/issues/3901~~
~~The following works on older Makie but not the latest one, I think it's a bug~~
```julia
julia> h = Hist1D(;binedges=0:1, bincounts=[0.1], sumw2=[0.1])
edges: [0.0, 1.0]
bin counts: [0.1]
total count: 0.1
julia> stephist(h); errorbars!(h); current_figure()
```
```julia
julia> stephist(h); errorbars!(h; error_function=FHist.pearson_err); current_figure()
```
> `clamp_errors` options for Makie Errorbars and `clamp_bincounts` for histograms
